# Generated by Django 4.2.4 on 2023-08-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_dadospaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_hdl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_ldl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_gordura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_musculo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='trigliceridios',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('carboidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('gorduras', models.FloatField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='opcao')),
                ('descricao', models.TextField()),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.refeicao')),
            ],
        ),
    ]
